<a href="https://colab.research.google.com/github/Phillolife/MLpython/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# type는 데이터 성질 파악.
# 배열에 대한 .shape 는 배열의 차원과 크기를 tuple(튜플) 형태로 나타냄.

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # 1차원에서 3개의 데이터터

array2 = np.array([[1,2,3,4],
                   [5,6,7,8]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) # 2차원에서 2개의 행과 4개의 열

array3 = np.array([[1,2,3,4]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array4 = np.array([[[1,2,3,4]]])
print('array4 type:', type(array4))
print('array4 array 형태:', array4.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 4)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 4)
array4 type: <class 'numpy.ndarray'>
array4 array 형태: (1, 1, 4)


In [4]:
# .ndim 명령어로 n차원 확인 가능
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원, array4:{:3}차원'.format(array1.ndim, array2.ndim, array3.ndim, array4.ndim))

# array() 함수에서 리스트 []= 1차원, [[]]= 2차원, [[[]]]= 3차원 으로 표기된다.

array1:1차원, array2:2차원, array3: 2차원, array4:  3차원


In [5]:
list1 = [1,2,3]
print(type(list1))
# list type을 ndarray 로 변경
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)
# 변경된 ndarray 내의 데이터 값은 int64형 임.

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
# 만약 다른 데이터 유형의 리스트를 ndarray로 변경 했을 때는 더 큰 데이터 타입으로 일괄 적용.
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) # int형 값과 문자열이 섞여 있을 때 모두 데이터 값이 더 큰 문자열 '1','2','test' 으로 변환됨.

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # int(정수)형 값과 float(실수)형이 섞여 있을 때 모두 데이터 값이 더 큰 float형 1. , 2. , 3. 으로 변환됨.

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
# ndarray 내 데이터값의 타입 변경 astype() 매서드 // 사용이유는 머신러닝에 사용되는 메모리 절약.

# 정수형을 실수형으로 변환.
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# 실수형 변환을 정수형(32bit)으로 재재변환.
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

# 실수형 배열을 정수형(64bit)로 변환. 
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int64')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int64


In [8]:
# arange() 는 파이썬 표준함수 range와 유사한 기능으로 0부터 함수 인자값 -1까지 표기 / ex) arange(5) = [0,1,2,3,4]
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) # 1차원 내 10개의 데이터

sequence_array2 = np.arange(2,5) # 초기값 설정도 가능능
print(sequence_array2)
print(sequence_array2.shape) 

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[2 3 4]
(3,)


In [9]:
# .zeros()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환.
# .ones()는 1로 채움. / 함수인자로 dtype를 정해주지 않으면 float64형이 디폴트 값으로 제공됨.

zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)



[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
# .reshape() 매서드는 ndarray를 특정 차원 및 크기로 변환.
# \n = 칸 넘기기기

array1 = np.arange(18)
print('array1:\n', array1)

array2 = array1.reshape(3,6)
print('array2:\n', array2)

array3 = array1.reshape(9,2)
print('array3:\n', array3)

# (로우,칼럼) = (열,행)

array1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
array2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
array3:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]


In [11]:
# 4차원 배열 만들기

array1 = np.arange(16)
array3d = array1.reshape((2,2,2,2))
print('array3d:\n', array3d.tolist())  # .tolist() 는 일렬로 시각화

# 3차원 ndarray를 2차원 ndarray로 변환
# -1 인자를 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해 줌.

array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원ndarray를 2차원 ndarray로 변환

array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[[0, 1], [2, 3]], [[4, 5], [6, 7]]], [[[8, 9], [10, 11]], [[12, 13], [14, 15]]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15]]
array5 shape: (16, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15]]
array6 shape: (16, 1)


In [12]:
# Numpy_ndarray의 Indexing
# 1 - 단일 값 추출

array1 = np.arange(start=1,stop=10)
print(array1)
value = array1[2] # Index 2번째 값
print('value:', value)
print(type(value))  # array1[2]의 타입은 더 이상 ndarray 타입이 아닌 nadarray 내의 데이터값을 의미함.
print('맨 뒤의 값:', array1[-1], '맨 뒤의 두 번째 값', array1[-2])

[1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤의 두 번째 값 8


In [13]:
# 다차원 배열 ndarray 에서 단일 값 추출

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0 index 가리키는 값:', array2d[0,0])
print('(row=0, col=1 index 가리키는 값:', array2d[0,1])
print('(row=1, col=1 index 가리키는 값:', array2d[1,1] )
print('(row=2, col=1 index 가리키는 값:', array2d[2,1] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0 index 가리키는 값: 1
(row=0, col=1 index 가리키는 값: 2
(row=1, col=1 index 가리키는 값: 5
(row=2, col=1 index 가리키는 값: 8


In [14]:
# Index 슬라이싱(slicing)

array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3)) # 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입이다.

array1 = np.arange(1,10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [15]:
# 2차원 ndarray 슬라이싱

array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, :2]\n', array2d[1:3, :2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, :2]
 [[4 5]
 [7 8]]


In [16]:
# Boolean Indexing

array1d = np.arange(1,10)
array3 = array1d[array1d > 5]
print(array3)

array1d >5

[6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True])

In [17]:
# np.sort() / ndarray.sort()

org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort()호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('ndarray.sort()호출 후 반환된 정렬 행렬: ', sort_array2)
print('ndarray.sort()호출 후 원본 행렬: ', org_array)

# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 sort():', sort_array1_desc)

# 행렬이 2차원 이상일 경우 axis 축 값을 설정하여 로우,칼럼 방향 정렬 수행 가능

array2d = np.array([[8, 12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0) # axis=0 은 로우(행)방향
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

원본 행렬: [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort()호출 후 원본 행렬: [3 1 9 5]
ndarray.sort()호출 후 반환된 정렬 행렬:  None
ndarray.sort()호출 후 원본 행렬:  [1 3 5 9]
내림차순 sort(): [9 5 3 1]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [20]:
# 선형대수 연산 - 행렬 내적(행렬의 곱) 구하기

A = np.array( [[1,2,3],
               [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A, B)  # np.dot 는 행렬 내적(행렬 간의 곱셈)을 구하는 파라미터터
print('행렬 내적 결과과:\n', dot_product)

행렬 내적 결과과:
 [[ 58  64]
 [139 154]]
[[ 58]
 [ 64]
 [139]
 [154]]


In [22]:
# 선형대수 연산 - 전치 행렬구하기
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A:\n', A)
print('A의 전치행렬:\n', transpose_mat)

A:
 [[1 2]
 [3 4]]
A의 전치행렬:
 [[1 3]
 [2 4]]
