<a href="https://colab.research.google.com/github/Phillolife/MLpython/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# type는 데이터 성질 파악.
# 배열에 대한 .shape 는 배열의 차원과 크기를 tuple(튜플) 형태로 나타냄.

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # 1차원에서 3개의 데이터터

array2 = np.array([[1,2,3,4],
                   [5,6,7,8]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) # 2차원에서 2개의 행과 4개의 열

array3 = np.array([[1,2,3,4]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array4 = np.array([[[1,2,3,4]]])
print('array4 type:', type(array4))
print('array4 array 형태:', array4.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 4)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 4)
array4 type: <class 'numpy.ndarray'>
array4 array 형태: (1, 1, 4)


In [ ]:
# .ndim 명령어로 n차원 확인 가능
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원, array4:{:3}차원'.format(array1.ndim, array2.ndim, array3.ndim, array4.ndim))

# array() 함수에서 리스트 []= 1차원, [[]]= 2차원, [[[]]]= 3차원 으로 표기된다.

array1:1차원, array2:2차원, array3: 2차원, array4:  3차원


In [ ]:
list1 = [1,2,3]
print(type(list1))
# list type을 ndarray 로 변경
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)
# 변경된 ndarray 내의 데이터 값은 int64형 임.

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
# 만약 다른 데이터 유형의 리스트를 ndarray로 변경 했을 때는 더 큰 데이터 타입으로 일괄 적용.
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) # int형 값과 문자열이 섞여 있을 때 모두 데이터 값이 더 큰 문자열 '1','2','test' 으로 변환됨.

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # int(정수)형 값과 float(실수)형이 섞여 있을 때 모두 데이터 값이 더 큰 float형 1. , 2. , 3. 으로 변환됨.

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
# ndarray 내 데이터값의 타입 변경 astype() 매서드 // 사용이유는 머신러닝에 사용되는 메모리 절약.

# 정수형을 실수형으로 변환.
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# 실수형 변환을 정수형(32bit)으로 재재변환.
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

# 실수형 배열을 정수형(64bit)로 변환. 
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int64')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int64


In [ ]:
# arange() 는 파이썬 표준함수 range와 유사한 기능으로 0부터 함수 인자값 -1까지 표기 / ex) arange(5) = [0,1,2,3,4]
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) # 1차원 내 10개의 데이터

sequence_array2 = np.arange(2,5) # 초기값 설정도 가능능
print(sequence_array2)
print(sequence_array2.shape) 

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[2 3 4]
(3,)
